### ISSUE TITLE
Do we need CMAKE_CXX_STANDARD 11 to build

### ISSUE THREAD

**Issue by yanyh15** [passlab/ompparser#72]
I turned this off. It builds.

**Comment by ouankou** [comment]
We do need this flag (commit https://github.com/passlab/ompparser/commit/b902ecf5223752fa1fcd8bae4eddec1cb8d18e11). Otherwise, GCC 5 on Ubuntu 16.04 will complain `to_string` is not a member of `std`. It will cause a failing compilation of the REX compiler. GCC 7 and later don't require this flag since they enable C++14 by default.

`std::to_string` is available since C++11.
https://en.cppreference.com/w/cpp/string/basic_string/to_string

**Comment by yanyh15** [comment]
Thank you.
